version: '3.7'

services:
  web:
    container_name: hub_web
    ports:
      - 3000:3000
    build: ./web
    depends_on:
      - db
      - myphpadmin
      - cron-run
    env_file:
      - ./web/.env.production
    volumes:
      - ./mysql/backups:/backups
    networks:
      - network
    restart: always

  db:
    image: mysql:latest
    container_name: hub_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hub
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - network
    restart: always
      
  myphpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: hub_phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - network
    restart: always

  cron-run:
    container_name: hub_cron
    build:
      context: ./cron
    volumes:
      - ./mysql/backups:/backups
    depends_on:
      - db
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  database:
    driver: local
  backups:
    driver: local
