version: "3.7"

services:
  web:
    container_name: hub_web
    ports:
      - 3000:3000
    build:
      dockerfile: Dockerfile
    env_file:
      - .env.production
    networks:
      - network
    depends_on:
      - db
    restart: always

  db:
    image: mysql:latest
    container_name: hub_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hub
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  myphpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: hub_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80

networks:
  network:
    driver: bridge

volumes:
  db:
    driver: local
