version: "2.2"

services:
  # web:
  #   container_name: hub_web
  #   ports:
  #     - 3000:3000
  #   build: .
  #   depends_on:
  #     db:
  #       condition: service_started
  #   env_file:
  #     - .env.production
  #   networks:
  #     - network
  #   restart: always

  db:
    image: mysql:latest
    container_name: hub_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hub
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - network

  myphpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: hub_phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db:
    driver: local
